services:
  api:
    build:
      context: .
      dockerfile: ./ExchangeBrokerX.Api/Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    volumes:
      - ./orderBooks.json:/app/orderBooks.json
      - ./exchangesBalance.json:/app/exchangesBalance.json